### ISSUE TITLE
modules mounted not change status on tables.

### ISSUE THREAD

**Issue by septianw** [septianw/jas#1]
when module enabled at module-enabled file, it doesn't change status at module table. Status field should change everytime module status change.

**Comment by septianw** [comment]
Commit number 731a002ef359b651619c3dccf5bb78d89b01373a will cover some of this issue but not implemented yet. I need somebody to implement and test the function.

**Comment by RadesGhani** [comment]
I've found something fishy with the SetModuleMetadata function in modules.go which may cause this abnormality.

To be exact in modules.go at line 42 there's this query :

(https://github.com/septianw/jas/blob/34d9b4fce0fcb2f386aca1696213fc20917ddd8c/modules.go#L42)

I never heard of UPDATE TABLE query, and I has been looking for it for a while now but no luck. Shouldn't it be UPDATE table_name? If so I think the correct query will be like this :

```
qs := `UPDATE modules SET version = '%s', status = '%s', sopath = '%s' WHERE name = %s;`
q := fmt.Sprintf(qs, meta.Version, meta.Status, meta.Sopath, meta.Name)
```

I have tried to try it myself, but I got another module version didn't match problem. When I tried to rebuild everything this time I found another issue : 

After running the jas in maintenance mode and execute migrate file, the migrate file say :

> Database structure migration success

 However when I check the database, there's just a single table called gorp_migrations. I'm hesitating to make a new issue since it's probably just a problem with the git repository being outdated. If that's the case can you please update the repo? If after that the problem persist I might create a new issue.
![image](https://user-images.githubusercontent.com/23325122/69593164-f5661400-102a-11ea-8ec2-9955547c9e41.png)

**Comment by septianw** [comment]
@RadesGhani Thank you for your help. your solution might merge to v1.1
